<div class="tve_lg_input_container tve-new-radio tve_lg_radio tve-draggable tve-droppable" draggable="true" data-columns="4">
	<p class="tve_lg_radio_label tcb-editable-label" data-group-editing-parent=".tve_lg_radio">
		<?php echo __( 'Radio Label', 'thrive-cb' ); ?>
	</p>
	<div class="tve-radio-grid">

		<div class="tve_lg_radio_wrapper" data-value="default">
			<input type="radio" name="radio" data-label-value="true" value="Option A"/>
			<label></label>
			<span class="tve-checkmark"></span>
			<p class="tve-input-option-text"><?php echo __( 'Option A', 'thrive-cb' ); ?></p>
		</div>

		<div class="tve_lg_radio_wrapper" data-value="default">
			<input type="radio" name="radio" data-label-value="true" value="Option B"/>
			<label></label>
			<span class="tve-checkmark"></span>
			<p class="tve-input-option-text"><?php echo __( 'Option B', 'thrive-cb' ); ?></p>
		</div>

		<div class="tve_lg_radio_wrapper" data-value="default">
			<input name="radio" type="radio" data-label-value="true" value="Option C"/>
			<label></label>
			<span class="tve-checkmark"></span>
			<p class="tve-input-option-text"><?php echo __( 'Option C', 'thrive-cb' ); ?></p>
		</div>

		<div class="tve_lg_radio_wrapper" data-value="default">
			<input name="radio" type="radio" data-label-value="true" value="Option D"/>
			<label></label>
			<span class="tve-checkmark"></span>
			<p class="tve-input-option-text"><?php echo __( 'Option D', 'thrive-cb' ); ?></p>
		</div>

	</div>
</div>