<div class="thrv-leads-screen-filler tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content tve_empty_dropzone" data-css="tve-u-15da26e5cb0" style="">
<div class="thrv_wrapper thrv_icon tcb-icon-display tve_evt_manager_listen tve_et_click tve_ea_thrive_leads_form_close" data-css="tve-u-15da26b73a7" data-tcb-events="__TCB_EVENT_[{&quot;a&quot;:&quot;thrive_leads_form_close&quot;,&quot;t&quot;:&quot;click&quot;}]_TNEVE_BCT__">
<svg class="tcb-icon" viewBox="0 0 30 32" data-name="close"><path d="M0.655 2.801l1.257-1.257 27.655 27.655-1.257 1.257-27.655-27.655z"></path><path d="M28.31 1.543l1.257 1.257-27.655 27.655-1.257-1.257 27.655-27.655z"></path></svg>
</div>
<div class="thrv_wrapper thrv-page-section" data-css="tve-u-15da26dc524">
<div class="tve-page-section-out" data-css="tve-u-15e0e8657cf"></div>
<div class="tve-page-section-in tve_empty_dropzone" data-css="tve-u-15e0e875745"><div class="thrv_wrapper thrv_contentbox_shortcode thrv-content-box" style="" data-css="tve-u-15e0eb15573">
<div class="tve-content-box-background" data-css="tve-u-15e0eb1d636"></div>
<div class="tve-cb" data-css="tve-u-15e0eb21afe"></div>
</div><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-15e0ea07f45"><div class="tcb-flex-row tcb-resized tcb--cols--2" data-css="tve-u-15e0e8d8002"><div class="tcb-flex-col" data-css="tve-u-15e0e8df8fb" style=""><div class="tcb-col tve_empty_dropzone" style=""><div class="thrv_wrapper tve_image_caption" data-css="tve-u-15e0e8d608b" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2134" alt="" width="181" height="285" title="47_set_image" data-id="2134" src="{tve_leads_base_url}/images/47_set_image.png" style="width: 100%;"><div class="tve-image-overlay" data-css="tve-u-15e0eb0a1da"></div></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-15e0e8df8fe" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-15e0eb93d15"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-15e0e8d007a"><p data-css="tve-u-15e0e8fb84e" data-default="Enter your text here..." style="text-align: left;"><span style="color: rgb(243, 80, 0);"><strong>Drive more sales</strong></span><strong> </strong>by building optimized landing pages</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone tcb-mobile-hidden" style="" data-css="tve-u-15e0eaa037f"><p data-css="tve-u-15e0e912b5c" data-default="Enter your text here..."><span style="color: rgb(255, 255, 255);">Get access to tested tips for building better landing pages in record time.</span></p></div><div class="thrv_wrapper thrv-button tve_ea_tl_state_switch" data-css="tve-u-15e0e93640d" style="">
<a href="" class="tcb-button-link tve_evt_manager_listen tve_et_click" data-tcb-events="|open_state_2|">
<span class="tcb-button-texts"><span class="tcb-button-text thrv-inline-text" data-css="tve-u-15e0e94c53e">Yes, I want the FREE Download</span></span>
</a>
</div></div></div></div></div></div>
</div>
</div>